# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#default_platform(:ios)
#
#platform :ios do
#  desc "Push a new beta build to TestFlight"
#  lane :beta do
#    increment_build_number(xcodeproj: "cursos_croplifela.xcodeproj")
#    build_app(workspace: "cursos_croplifela.xcworkspace", scheme: "cursos_croplifela")
#    upload_to_testflight
#  end
#end



default_platform(:ios)

platform :ios do
  def updateVersion(options)
    if options[:version]
      version = options[:version]
    else
      version = prompt(text: "Enter the version type or specific version\n(major, minor, patch or 1.0.0): ")
    end

    re = /\d+.\d+.\d+/
    versionNum = version[re, 0]

    if (versionNum)
      increment_version_number(
        version_number: versionNum
      )
    elsif (version == 'major' || version == 'minor' || version == 'patch')
      increment_version_number(
        bump_type: version
      )
    else
      UI.user_error!("[ERROR] Wrong version!!!!!!")
    end
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    cert
    sigh(force: true)
    updateVersion(options)

    #increment_build_number(xcodeproj: "kumoncho.xcodeproj")
    #build_app(workspace: "kumoncho.xcworkspace", scheme: "kumoncho")
    #upload_to_testflight

    increment_build_number(xcodeproj: "cursos_croplifela.xcodeproj")
    build_app(workspace: "cursos_croplifela.xcworkspace", scheme: "cursos_croplifela")
    upload_to_testflight

  end

  desc "Push a new release build to the App Store"
  lane :release do |options|
    cert
    sigh(force: true)
    updateVersion(options)

    increment_build_number(xcodeproj: "cursos_croplifela.xcodeproj")
    build_app(workspace: "cursos_croplifela.xcworkspace", scheme: "cursos_croplifela")
    upload_to_app_store(
      force: true,
      reject_if_possible: true,
      skip_metadata: false,
      skip_screenshots: true,
      languages: ['en-US'],
      release_notes: {
        "default" => "bug fixed",
        "en-US" => "bug fixed",
      },
      submit_for_review: true,
      automatic_release: true,
      submission_information: {
        #add_id_info_uses_idfa: true,
        #add_id_info_serves_ads: true,
        #add_id_info_tracks_install: true,
        #add_id_info_tracks_action: false,
        #add_id_info_limits_tracking: true,
        #export_compliance_encryption_updated: false,


        add_id_info_limits_tracking: true,
        add_id_info_serves_ads: false,
        add_id_info_tracks_action: true,
        add_id_info_tracks_install: true,
        add_id_info_uses_idfa: true,
        content_rights_has_rights: true,
        content_rights_contains_third_party_content: true,
        export_compliance_platform: 'ios',
        export_compliance_compliance_required: false,
        export_compliance_encryption_updated: false,
        export_compliance_app_type: nil,
        export_compliance_uses_encryption: false,
        export_compliance_is_exempt: false,
        export_compliance_contains_third_party_cryptography: false,
        export_compliance_contains_proprietary_cryptography: false,
        export_compliance_available_on_french_store: false


      }
    )
  end
end
